services:
  - type: web
    name: my-dash-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      - key: DASH_ENV
        value: production
    region: oregon
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
